import type { RecordFieldDefs } from "../../types";

/**
 * Batch Header Record — Original statement.
 * Source: "File format_Regular" sheet, Form 24G_File_Format_version 1.9.
 *
 * Note: a handful of fields carry contradictory remarks between the Regular
 * sheet and the Correction_M/X sheets in the source workbook itself (e.g.
 * field 18, Responsible Person Name). This file transcribes the Regular
 * sheet's own wording; variant-specific wording is captured in the
 * correction overlay files rather than silently reconciled.
 */
export const bhFields: RecordFieldDefs = [
  { index: 1, name: "Line Number", dataType: "INTEGER", length: 9, mandatory: "M", fyScope: "always", remarks: "Running sequence number for each line in the statement." },
  { index: 2, name: "Record Type", dataType: "CHAR", length: 2, mandatory: "M", constant: "BH", fyScope: "always", remarks: 'Value should be "BH" signifying the Batch Header Record.' },
  { index: 3, name: "Batch Number", dataType: "INTEGER", length: 9, mandatory: "M", constant: "1", fyScope: "always", remarks: "Value should always be 1." },
  { index: 4, name: "Transaction Type", dataType: "NA", mandatory: "NA", fyScope: "always", remarks: "No value should be specified. For future use (Original statements only)." },
  { index: 5, name: "Accounts Office Identification No. (AIN)", dataType: "CHAR", length: 7, mandatory: "M", fyScope: "always", pattern: "^\\d{7}$", remarks: "Must match Field 7 of the File Header (FH)." },
  { index: 6, name: "Last Accounts Office Identification No. (AIN)", dataType: "NA", mandatory: "NA", fyScope: "always", remarks: "No value should be specified. For future use." },
  { index: 7, name: "AO_Name", dataType: "CHAR", length: 75, mandatory: "M", fyScope: "always", remarks: "Name of Accounts Office, e.g. 'PAO, Chief Labour Commissioner'." },
  { index: 8, name: "AO_Address Line 1 OR Flat/Door/Block Number", dataType: "CHAR", length: 25, mandatory: "M", fyScope: "always", remarks: "Address of AO. Labeled 'Flat/Door/Block Number' from FY2026-27 onward." },
  { index: 9, name: "AO_Address Line 2 OR Name of Premises / Building", dataType: "CHAR", length: 25, mandatory: "O", fyScope: "always", remarks: "Address of AO. Labeled 'Name of Premises / Building' from FY2026-27 onward." },
  { index: 10, name: "AO_Address Line 3 OR Road/ Street/ Lane", dataType: "CHAR", length: 25, mandatory: "O", fyScope: "always", remarks: "Address of AO. Labeled 'Road/ Street/ Lane' from FY2026-27 onward." },
  { index: 11, name: "AO_Address Line 4 OR Area/ Location", dataType: "CHAR", length: 25, mandatory: "O", fyScope: "always", remarks: "Address of AO. Labeled 'Area/ Location' from FY2026-27 onward." },
  { index: 12, name: "AO_City", dataType: "CHAR", length: 25, mandatory: "M", fyScope: "always", remarks: "City/District of AO." },
  { index: 13, name: "AO_State", dataType: "CHAR", length: 2, mandatory: "M", fyScope: "always", annexureRef: "state", remarks: "Numeric state/UT code of AO office." },
  { index: 14, name: "AO_PIN", dataType: "CHAR", length: 6, mandatory: "M", fyScope: "always", pattern: "^\\d{6}$", remarks: "PIN code of AO. Must be >= 110001, and not 000000 or 999999." },
  { index: 15, name: "STD Code", dataType: "CHAR", length: 5, mandatory: "M", fyScope: "always", remarks: "STD Code of AO. Must be '91' if a mobile number is used instead of a landline." },
  { index: 16, name: "Phone No.", dataType: "CHAR", length: 10, mandatory: "M", fyScope: "always", pattern: "^\\d{1,10}$", remarks: "Phone number, numeric only, up to 10 digits (landline numbers are often shorter than 10)." },
  { index: 17, name: "Email ID", dataType: "CHAR", length: 75, mandatory: "M", fyScope: "always", pattern: "^[^\\s^]+@[^\\s^]+\\.[^\\s^]+$", remarks: "Must contain @ and ., each preceded/succeeded by at least one character; no '^' or spaces." },
  { index: 18, name: "Responsible Person Name", dataType: "CHAR", length: 75, mandatory: "M", mandatoryByFyScope: { f137: "NA" }, fyScope: "always", remarks: "Name of person responsible for furnishing the statement. Applicable up to FY2025-26; no value from FY2026-27 onward (see field 76-78 name split)." },
  { index: 19, name: "Responsible Person Designation", dataType: "CHAR", length: 25, mandatory: "M", fyScope: "always", remarks: "Designation of the responsible person." },
  { index: 20, name: "Financial Year", dataType: "CHAR", length: 4, mandatory: "M", fyScope: "always", pattern: "^(19|20)\\d{2}$", remarks: "e.g. 2005 for FY2005-06. Must be >= 2005 and <= current year." },
  { index: 21, name: "Last Financial Year", dataType: "NA", mandatory: "NA", fyScope: "always", remarks: "No value should be specified. For future use." },
  { index: 22, name: "AO Category", dataType: "CHAR", length: 2, mandatory: "M", fyScope: "always", annexureRef: "ddoCategory", remarks: "Per Annexure 2 (Central govt. = A, State Government = S)." },
  { index: 23, name: "Last AO Category", dataType: "NA", mandatory: "NA", fyScope: "always", remarks: "No value should be specified. For future use." },
  { index: 24, name: "Filler 1", dataType: "NA", mandatory: "NA", fyScope: "always", remarks: "No value should be specified. For future use (Original statements only)." },
  { index: 25, name: "Filler 2", dataType: "NA", mandatory: "NA", fyScope: "always", remarks: "No value should be specified. For future use." },
  { index: 26, name: "Filler 3", dataType: "NA", mandatory: "NA", fyScope: "always", remarks: "No value should be specified. For future use." },
  { index: 27, name: "Filler 4", dataType: "NA", mandatory: "NA", fyScope: "always", remarks: "No value should be specified. For future use." },
  { index: 28, name: "No. of Transactions", dataType: "INTEGER", length: 9, mandatory: "M", fyScope: "always", minValue: 1, remarks: "Must equal total DDO (TD) record count in the statement. Count >= 1." },
  { index: 29, name: "Total TDS/TCS amount reported", dataType: "DECIMAL", length: [15, 2], mandatory: "M", fyScope: "always", remarks: "Sum of BAS_TAX, SUR, EDU_CESS across all TD records. Must be >= 0.00." },
  { index: 30, name: "Original RRR No.", dataType: "NA", mandatory: "NA", fyScope: "always", remarks: "No value should be specified for Original statements." },
  { index: 31, name: "Previous RRR No.", dataType: "NA", mandatory: "NA", fyScope: "always", remarks: "No value should be specified for Original statements." },
  { index: 32, name: "Provisional Receipt Number", dataType: "NA", mandatory: "NA", fyScope: "always", remarks: "No value should be specified. Assigned by the FVU/portal." },
  { index: 33, name: "Provisional Receipt Date", dataType: "NA", mandatory: "NA", fyScope: "always", remarks: "No value should be specified. Assigned by the FVU/portal." },
  { index: 34, name: "Month of Transfer voucher", dataType: "INTEGER", length: 2, mandatory: "M", fyScope: "always", annexureRef: "month", remarks: "1-12; must be <= current month." },
  { index: 35, name: "Responsible person Address Line 1", dataType: "CHAR", length: 25, mandatory: "M", fyScope: "always", remarks: "Address of Responsible person." },
  { index: 36, name: "Responsible person Address Line 2", dataType: "CHAR", length: 25, mandatory: "O", fyScope: "always", remarks: "Address of Responsible person." },
  { index: 37, name: "Responsible person Address Line 3", dataType: "CHAR", length: 25, mandatory: "O", fyScope: "always", remarks: "Address of Responsible person." },
  { index: 38, name: "Responsible person Address Line 4", dataType: "CHAR", length: 25, mandatory: "O", fyScope: "always", remarks: "Address of Responsible person." },
  { index: 39, name: "Responsible person_City", dataType: "CHAR", length: 25, mandatory: "M", fyScope: "always", remarks: "City/District of Responsible person." },
  { index: 40, name: "Responsible person_State", dataType: "CHAR", length: 2, mandatory: "M", fyScope: "always", annexureRef: "state", remarks: "Numeric state/UT code." },
  { index: 41, name: "Responsible person_PIN", dataType: "CHAR", length: 6, mandatory: "M", fyScope: "always", pattern: "^\\d{6}$", remarks: "PIN of Responsible person address. Must be >= 110001." },
  { index: 42, name: "Responsible person STD Code", dataType: "CHAR", length: 5, mandatory: "O", fyScope: "always", remarks: "5 digits for landline; '91' for mobile." },
  { index: 43, name: "Responsible person Phone No.", dataType: "CHAR", length: 10, mandatory: "O", fyScope: "always", pattern: "^\\d{1,10}$", remarks: "Numeric only, up to 10 digits (landline numbers are often shorter than 10). Either phone or mobile number is mandatory." },
  { index: 44, name: "Responsible person E-mail id", dataType: "CHAR", length: 75, mandatory: "M", fyScope: "always", pattern: "^[^\\s^]+@[^\\s^]+\\.[^\\s^]+$", remarks: "Same email formatting rules as field 17." },
  { index: 45, name: "Mobile no. of Responsible person", dataType: "INTEGER", length: 10, mandatory: "O", mandatoryByFyScope: { f137: "M" }, fyScope: "always", pattern: "^\\d{10}$", remarks: "Either phone or mobile is mandatory pre-FY2026-27; mandatory 10-digit mobile from FY2026-27 onward." },
  { index: 46, name: "Country Code", dataType: "CHAR", length: 3, mandatory: "NA", mandatoryByFyScope: { f137: "M" }, fyScope: "always", annexureRef: "country", remarks: "Applicable from FY2026-27 onward per Annexure 8." },
  { index: 47, name: "State name", dataType: "CHAR", length: 2, mandatory: "O", fyScope: "always", annexureRef: "state", remarks: "Mandatory (enforced by the FVU as error F137/F24G-FV-2134) when AO Category = State Government; otherwise optional." },
  { index: 48, name: "Ministry/ Department name", dataType: "CHAR", length: 3, mandatory: "O", mandatoryByFyScope: {}, fyScope: "always", annexureRef: "ministry", remarks: "Numeric ministry code (Annexure 3). Mandatory when AO Category = Central government." },
  { index: 49, name: "Sub Ministry name", dataType: "CHAR", length: 3, mandatory: "O", fyScope: "always", annexureRef: "subMinistry", remarks: "Numeric sub-ministry code (Annexure 4). Mandatory when AO Category = Central government." },
  { index: 50, name: "Sub Ministry name (Others)", dataType: "CHAR", length: 150, mandatory: "O", fyScope: "always", remarks: 'Required when Sub Ministry code = "99" (Other).' },
  { index: 51, name: "Count of 24Q transaction", dataType: "INTEGER", length: 9, mandatory: "M", fyScope: "always", remarks: "0 if none for Form 24Q." },
  { index: 52, name: "Control total of tax deducted/collected for 24Q", dataType: "DECIMAL", length: 15, mandatory: "M", fyScope: "always", remarks: "Sum across TD records for Form 24Q. Must be >= 0.00." },
  { index: 53, name: "Total TDS/TCS remitted to Government account (AG/Pr CCA) for 24Q", dataType: "DECIMAL", length: 15, mandatory: "M", fyScope: "always", remarks: "Sum across TD records for Form 24Q. Must be >= 0.00." },
  { index: 54, name: "Count of 26Q transaction", dataType: "INTEGER", length: 9, mandatory: "M", fyScope: "always", remarks: "0 if none for Form 26Q." },
  { index: 55, name: "Control total of tax deducted/collected for 26Q", dataType: "DECIMAL", length: 15, mandatory: "M", fyScope: "always", remarks: "Sum across TD records for Form 26Q. Must be >= 0.00." },
  { index: 56, name: "Total TDS/TCS remitted to Government account (AG/Pr CCA) for 26Q", dataType: "DECIMAL", length: 15, mandatory: "M", fyScope: "always", remarks: "Sum across TD records for Form 26Q. Must be >= 0.00." },
  { index: 57, name: "Count of 27Q transaction", dataType: "INTEGER", length: 9, mandatory: "M", fyScope: "always", remarks: "0 if none for Form 27Q." },
  { index: 58, name: "Control total of tax deducted/collected for 27Q", dataType: "DECIMAL", length: 15, mandatory: "M", fyScope: "always", remarks: "Sum across TD records for Form 27Q. Must be >= 0.00." },
  { index: 59, name: "Total TDS/TCS remitted to Government account (AG/Pr CCA) for 27Q", dataType: "DECIMAL", length: 15, mandatory: "M", fyScope: "always", remarks: "Sum across TD records for Form 27Q. Must be >= 0.00." },
  { index: 60, name: "Count of 27EQ transaction", dataType: "INTEGER", length: 9, mandatory: "M", fyScope: "always", remarks: "0 if none for Form 27EQ." },
  { index: 61, name: "Control total of tax deducted/collected for 27EQ", dataType: "DECIMAL", length: 15, mandatory: "M", fyScope: "always", remarks: "Sum across TD records for Form 27EQ. Must be >= 0.00." },
  { index: 62, name: "Total TDS/TCS remitted to Government account (AG/Pr CCA) for 27EQ", dataType: "DECIMAL", length: 15, mandatory: "M", fyScope: "always", remarks: "Sum across TD records for Form 27EQ. Must be >= 0.00." },
  { index: 63, name: "PAO registration no/ Accounts Office Registration Number", dataType: "INTEGER", length: 7, mandatory: "O", mandatoryByFyScope: { f137: "NA" }, fyScope: "always", remarks: "CRA-allotted PAO registration number. Not applicable from FY2026-27 onward." },
  { index: 64, name: "Count of Distinct DDOs", dataType: "INTEGER", length: 9, mandatory: "M", fyScope: "always", minValue: 1, remarks: "Distinct TANs across TD records. Count >= 1 (0 only if every DDO TAN is TANINVALID/TANNOTABVL/TANAPPLIED)." },
  { index: 65, name: "Total TDS/TCS remitted to Government account (AG/Pr CCA)", dataType: "DECIMAL", length: 15, mandatory: "M", fyScope: "always", remarks: "Sum across all TD records. Must be >= 0.00." },
  { index: 66, name: "Count of DDO records added", dataType: "INTEGER", length: 9, mandatory: "M", fyScope: "always", remarks: "DDO records with AIN-DDO mapping mode 'A'." },
  { index: 67, name: "Count of DDO records updated", dataType: "INTEGER", length: 9, mandatory: "M", fyScope: "always", remarks: "DDO records with AIN-DDO mapping mode 'U'." },
  { index: 68, name: "Count of DDO records deleted", dataType: "INTEGER", length: 9, mandatory: "M", fyScope: "always", remarks: "DDO records with AIN-DDO mapping mode 'D'." },
  { index: 69, name: "Receipt no.", dataType: "NA", mandatory: "NA", fyScope: "always", remarks: "No value should be specified." },
  { index: 70, name: "Filler 5", dataType: "NA", mandatory: "NA", fyScope: "always", remarks: "No value should be specified. For future use." },
  { index: 71, name: "Filler 6", dataType: "NA", mandatory: "NA", fyScope: "always", remarks: "No value should be specified. For future use (Original statements only)." },
  { index: 72, name: "TAN of Accounts Office", dataType: "CHAR", length: 10, mandatory: "NA", mandatoryByFyScope: { f137: "M" }, fyScope: "always", pattern: "^[A-Z0-9]{4}[0-9]{5}[A-Z]$", remarks: "Applicable from FY2026-27 onward; no value for FY2025-26 or prior." },
  { index: 73, name: "Special TAN (for State Government Category)", dataType: "CHAR", length: 10, mandatory: "O", fyScope: "f137", pattern: "^[A-Z0-9]{4}[0-9]{5}[A-Z]$", remarks: 'Applicable only when AO Category = "State Government", from FY2026-27 onward.' },
  { index: 74, name: "State AG Code (for State Government Category)", dataType: "ALPHANUMERIC", length: 20, mandatory: "O", fyScope: "f137", remarks: 'Applicable only when AO Category = "State Government", from FY2026-27 onward.' },
  { index: 75, name: "Filler 6", dataType: "NA", mandatory: "NA", fyScope: "always", remarks: "No value should be specified. For future use." },
  { index: 76, name: "First Name of responsible person", dataType: "CHAR", length: 25, mandatory: "O", fyScope: "f137", remarks: "From FY2026-27 onward. Abbreviated values not allowed." },
  { index: 77, name: "Middle Name of responsible person", dataType: "CHAR", length: 25, mandatory: "O", fyScope: "f137", remarks: "From FY2026-27 onward. Abbreviated values not allowed." },
  { index: 78, name: "Last Name of responsible person", dataType: "CHAR", length: 25, mandatory: "M", fyScope: "f137", remarks: "From FY2026-27 onward. Abbreviated values not allowed." },
  { index: 79, name: "Country Code", dataType: "CHAR", length: 3, mandatory: "M", fyScope: "f137", annexureRef: "country", remarks: "From FY2026-27 onward, per Annexure 8." },
  { index: 80, name: "Batch Header Record Hash", dataType: "NA", mandatory: "NA", fyScope: "always", remarks: "No value should be specified. Computed by the FVU." },
];
