import type { RecordFieldDefs } from "../../types";

/**
 * File Header Record — Original statement.
 * Source: "File format_Regular" sheet, Form 24G_File_Format_version 1.9.
 */
export const fhFields: RecordFieldDefs = [
  {
    index: 1,
    name: "Line Number",
    dataType: "INTEGER",
    length: 9,
    mandatory: "M",
    fyScope: "always",
    remarks: "Running sequence number for each line in the file.",
  },
  {
    index: 2,
    name: "Record Type",
    dataType: "CHAR",
    length: 2,
    mandatory: "M",
    constant: "FH",
    fyScope: "always",
    remarks: 'Value should be "FH" signifying "File Header" record.',
  },
  {
    index: 3,
    name: "File Type",
    dataType: "CHAR",
    length: 4,
    mandatory: "M",
    constantByFyScope: { legacy: "24G", f137: "F137" },
    fyScope: "always",
    remarks: 'Value should be "24G" for FY2025-26 and before, "F137" from FY2026-27 onwards.',
  },
  {
    index: 4,
    name: "File Creation Date",
    dataType: "DATE",
    length: 8,
    mandatory: "M",
    fyScope: "always",
    remarks: "DDMMYYYY format. Must not be a future date.",
  },
  {
    index: 5,
    name: "Type of Statement",
    dataType: "CHAR",
    length: 1,
    mandatory: "M",
    constant: "O",
    fyScope: "always",
    remarks: 'Value should be "O" (Original).',
  },
  {
    index: 6,
    name: "Uploaded By",
    dataType: "CHAR",
    length: 1,
    mandatory: "M",
    constant: "D",
    fyScope: "always",
    remarks: 'Value should be "D".',
  },
  {
    index: 7,
    name: "Accounts Office Identification No. (AIN)",
    dataType: "CHAR",
    length: 7,
    mandatory: "M",
    fyScope: "always",
    pattern: "^\\d{7}$",
    remarks:
      "AIN allotted to the Accounts Office. 7 digits, cannot start with 0. Also carries a check digit enforced by the FVU (undocumented in the spec sheet): digit 7 must equal (digits 1-6 as a number) mod 7 — see src/lib/validation/ain.ts.",
  },
  {
    index: 8,
    name: "Number of Batches",
    dataType: "INTEGER",
    length: 9,
    mandatory: "M",
    constant: "1",
    fyScope: "always",
    remarks: "Number of batches in the file. Always 1.",
  },
  {
    index: 9,
    name: "FH Record Hash",
    dataType: "NA",
    mandatory: "NA",
    fyScope: "always",
    remarks: "No value should be specified. Computed by the FVU.",
  },
  {
    index: 10,
    name: "FVU Version",
    dataType: "NA",
    mandatory: "NA",
    fyScope: "always",
    remarks: "No value should be specified. Computed by the FVU.",
  },
  {
    index: 11,
    name: "FVU File Level Hash",
    dataType: "NA",
    mandatory: "NA",
    fyScope: "always",
    remarks: "No value should be specified. Computed by the FVU.",
  },
  {
    index: 12,
    name: "SAM Version",
    dataType: "NA",
    mandatory: "NA",
    fyScope: "always",
    remarks: "No value should be specified.",
  },
  {
    index: 13,
    name: "SAM File Level Hash",
    dataType: "NA",
    mandatory: "NA",
    fyScope: "always",
    remarks: "No value should be specified.",
  },
  {
    index: 14,
    name: "SCM Version",
    dataType: "NA",
    mandatory: "NA",
    fyScope: "always",
    remarks: "No value should be specified.",
  },
  {
    index: 15,
    name: "SCM File Level Hash",
    dataType: "NA",
    mandatory: "NA",
    fyScope: "always",
    remarks: "No value should be specified.",
  },
];
